# Generated by Django 4.2.5 on 2023-10-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_bot_id',
            field=models.IntegerField(default=0),
        ),
    ]
