# Generated by Django 4.2.5 on 2023-10-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_user_bot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_bot_pass',
            field=models.CharField(default='', max_length=100),
        ),
    ]
