# Generated by Django 4.2.5 on 2023-10-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_user_bot_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='salt',
            field=models.FloatField(default=0.0),
        ),
    ]
