# Generated by Django 4.2.5 on 2023-10-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='salt',
        ),
    ]
