# Generated by Django 4.2.5 on 2023-10-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_bot_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_bot_pass',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
