# Generated by Django 4.2.5 on 2023-10-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_product_alter_check_options_alter_printer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='order',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(default='default.pdf', upload_to=''),
        ),
        migrations.AlterField(
            model_name='printer',
            name='api_key',
            field=models.CharField(default=73, max_length=20, unique=True),
        ),
    ]
