# Generated by Django 4.2.5 on 2023-10-25 11:26

import checks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0004_alter_check_order_alter_check_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, default='default.pdf', null=True, upload_to=checks.models.get_check_file_path),
        ),
        migrations.AlterField(
            model_name='printer',
            name='api_key',
            field=models.CharField(default=57, max_length=20, unique=True),
        ),
    ]
